name: ubuntu
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # - run: |
    #     echo $PATH && \
    #     cd /usr/local/bin && \
    #     sudo curl https://github.com/dirkarnez/transfersh/releases/download/v1.0.0/transfersh-v1.0.0-ubuntu-latest.zip -L -O -J && \
    #     sudo unzip transfersh-v1.0.0-ubuntu-latest.zip && \
    #     sudo ls -R
        
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
        
    - name: Do cache
      id: my-cache
      uses: actions/cache@v3
      with:
        path: '/var/lib/docker/'
        key: ${{ runner.os }}-my-cache-key

    - name: This step is cached
      if: steps.my-cache.outputs.cache-hit != 'true'
      run: docker pull kkrizka/vivado:2021.1
        
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
